### ISSUE TITLE
Unity port

### ISSUE THREAD

**Issue by isshoujuuzou** [frangarcj/SMSplusVITA#1]
Hello, great man!

I'm sorry for disturbing your serious work here... But, I would like to ask you for a compiled version which could run on PSM for Unity. The current revitalize competition release gives that common error 'C2-blahblah' for unity users.

I appreciate so much your work and hope you make this emulator even more amazing.

**Comment by frangarcj** [comment]
It woks with unity for me.

Try this uvloader.bin 

https://github.com/frangarcj/SMSplusVITA/releases/download/1.3.1-Revitalize/uvloader.bin

**Comment by isshoujuuzou** [comment]
Thanks!

Keep up your good work, mate!
